### ISSUE TITLE
Fluidd UI not working propperly

### ISSUE THREAD

**Issue by darknblack** [dimalo/klipper-web-control-docker#10]
Hi

I can access the printer via Mainsail but not via Fluidd

![image](https://user-images.githubusercontent.com/8255516/122938738-994da800-d3a5-11eb-894e-efd7fb38455d.png)

I'm getting: Authorization error

and this: 
`{"error": {"code": 404, "message": "Not Found", "traceback": "Traceback (most recent call last):\n\n  File \"/home/klippy/moonraker-env/lib/python3.9/site-packages/tornado/web.py\", line 1681, in _execute\n    result = self.prepare()\n\n  File \"/home/klippy/moonraker/moonraker/app.py\", line 786, in prepare\n    raise tornado.web.HTTPError(404)\n\ntornado.web.HTTPError: HTTP 404: Not Found\n"}}`

whenever accessing the http://{moonraker_ip}/access

And this too in Fluidd
![image](https://user-images.githubusercontent.com/8255516/122943451-9eacf180-d3a9-11eb-813e-1d5a24b783b7.png)

Specs:
Raspberry Pi 4
Klipper v0.9.1-580-g478f26ca
Moonraker v0.6.0-160-gd3df568

**Comment by dimalo** [comment]
hi @darknblack,
maybe this is because my mainsail docker image has an included reverse proxy to moonrakers endpoints. So you can set up the printer with mainsails URL.
Using Fluidd's official image this functionality is not included though the klipper image has to expose it's port and has to be properly configured. In fluidd you enter moonraker's URL. This did not work well for me as well with fluidd.
That's why I switched back to build my own.

Fow nor you can as well, have a look into docker-compose, there is a commented out build section for fluidd.
this builds a similar image as mainsail, but with fluidd. fixed setup issues for me, as I only have to enter fluidd's URL as printer URL.

For more than one printer, this is a bit more tricky though.

**Comment by dimalo** [comment]
@darknblack not sure if your issue is fixed.

I did go to own fluidd builds as I like the reverse proxy config which saves a lot of time in setting up CORS etc...
