### ISSUE TITLE
fluidd - no connection to moonraker

### ISSUE THREAD

**Issue by VincentDugard** [dimalo/klipper-web-control-docker#29]
Hello ! I started the docker-compose, mainsail is working fine but fluidd say "no connection to moonraker"
I tried to build the image, and restart only fluidd when all the stack is up.

Any idea ?

**Comment by dimalo** [comment]
try using dimalo/fluidd
it's basically the same build as mainsail using an nginx reverse proxy within

cadriel/fluidd is built differently.

PS: instead of restarting try to recreate the fluidd container. Remove the "image: cadriel/fluidd" and uncomment the build key if you want to use your own (dimalo/fluidd is said build)
