### ISSUE TITLE
Moonraker GPIO support not working

### ISSUE THREAD

**Issue by TheSeven** [dimalo/klipper-web-control-docker#33]
It appears that Moonraker needs the `gpiod` module from libgpiod, not the `gpiod` PyPI package.
In the current images, both are installed, leading it to pick up the wrong one. Removing the PyPI package isn't sufficient however, because the `gpiod` module from libgpiod is being installed from the Debian repository, which contains Python 3.9, while the Docker image is based on Python 3.10.

The (verified working) path of least resistance appears to be downgrading the Docker image to `python:3.9-slim-bullseye` and removing the unnecessary installation of the `gpiod` PyPI package.
However the ideal solution would probably be reworking Moonraker to use the PyPI package instead. I'm not sure if there is any particular reason for them to stick with the old libgpiod module though.

**Comment by dimalo** [comment]
I did not try with moonraker but at least got an accelerometer to work with klipper, which needed to pass gpio and spi pins. Therefore I needed to tune the docker-compose.yml like [this](https://github.com/dimalo/klipper-web-control-docker/blob/develop/docker-compose-adxl345.yml)
Hope that can help. Please give it a try, otherwise we'll downgrade the image
